# Generated by Django 5.2 on 2025-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="value",
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
